import { FiDownload } from 'react-icons/fi'

const WATERMARK_BADGE = `<div style="position:fixed;bottom:12px;right:12px;z-index:2147483647;font-family:sans-serif;font-size:11px;line-height:1;color:rgba(0,0,0,0.55);background:rgba(255,255,255,0.85);padding:6px 10px;border-radius:6px;box-shadow:0 1px 4px rgba(0,0,0,0.15);pointer-events:none;user-select:none;">Built with WebNest Studio</div>`

// Backend-returned HTML may or may not be a full document. Inject a comment marker
// plus a small on-page badge so any downloaded file is traceable back to us, whether
// or not it has a closing </body> tag.
function addWatermark(htmlString) {
  const comment = `<!-- Generated by WebNest Studio (webneststudio.com) -->\n`
  if (/<\/body>/i.test(htmlString)) {
    return comment + htmlString.replace(/<\/body>/i, `${WATERMARK_BADGE}</body>`)
  }
  return comment + htmlString + WATERMARK_BADGE
}

function downloadHtml(htmlString, filename = 'webnest-ai-page.html') {
  const blob = new Blob([addWatermark(htmlString)], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export default function DownloadBar({ html, disabled }) {
  if (!html) return null
  return (
    <button
      type="button"
      disabled={disabled}
      onClick={() => downloadHtml(html)}
      className="inline-flex items-center gap-2 rounded-lg bg-ink-900 dark:bg-gold-400 px-3.5 py-2 text-xs font-semibold text-white dark:text-ink-950 transition-transform hover:scale-[1.03] disabled:cursor-not-allowed disabled:opacity-50"
    >
      <FiDownload className="h-3.5 w-3.5" /> Download HTML
    </button>
  )
}
