import { adminServices, adminPortfolio, adminTestimonials, adminFaqs, adminBlog } from '../../api/admin'

export const RESOURCE_CONFIGS = {
  services: {
    title: 'Services',
    api: adminServices,
    hasSlug: true,
    columns: ['title', 'slug', 'is_published'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true, hint: 'lowercase letters, numbers, dashes' },
      { name: 'short_description', label: 'Short Description', type: 'text', required: true },
      { name: 'full_description', label: 'Full Description', type: 'textarea' },
      { name: 'icon_url', label: 'Icon URL', type: 'text' },
      { name: 'tech_tags', label: 'Tech Tags (comma-separated)', type: 'tags' },
      { name: 'display_order', label: 'Display Order', type: 'number', default: 1 },
      { name: 'is_published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  portfolio: {
    title: 'Portfolio',
    api: adminPortfolio,
    hasSlug: true,
    columns: ['title', 'category', 'is_published'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true, hint: 'lowercase letters, numbers, dashes' },
      { name: 'category', label: 'Category', type: 'select', options: ['Web', 'AI', 'Enterprise'], required: true },
      { name: 'short_description', label: 'Short Description', type: 'text', required: true },
      { name: 'full_description', label: 'Full Description', type: 'textarea' },
      { name: 'tech_stack', label: 'Tech Stack (comma-separated)', type: 'tags' },
      { name: 'cover_image_url', label: 'Cover Image URL', type: 'text' },
      { name: 'gallery_urls', label: 'Gallery Image URLs (comma-separated)', type: 'tags' },
      { name: 'result_metrics', label: 'Result Metrics', type: 'text' },
      { name: 'client_name', label: 'Client Name', type: 'text' },
      { name: 'display_order', label: 'Display Order', type: 'number', default: 1 },
      { name: 'is_published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  testimonials: {
    title: 'Testimonials',
    api: adminTestimonials,
    columns: ['client_name', 'company', 'rating', 'is_published'],
    fields: [
      { name: 'client_name', label: 'Client Name', type: 'text', required: true },
      { name: 'company', label: 'Company', type: 'text' },
      { name: 'quote', label: 'Quote', type: 'textarea', required: true },
      { name: 'rating', label: 'Rating (1-5)', type: 'number', default: 5, min: 1, max: 5 },
      { name: 'avatar_url', label: 'Avatar URL', type: 'text' },
      { name: 'is_published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  faqs: {
    title: 'FAQs',
    api: adminFaqs,
    columns: ['question', 'category', 'is_published'],
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true },
      { name: 'answer', label: 'Answer', type: 'textarea', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'display_order', label: 'Display Order', type: 'number', default: 1 },
      { name: 'is_published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  blog: {
    title: 'Blog Posts',
    api: adminBlog,
    hasSlug: true,
    columns: ['title', 'slug', 'is_published'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true, hint: 'lowercase letters, numbers, dashes' },
      { name: 'excerpt', label: 'Excerpt', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'cover_image_url', label: 'Cover Image URL', type: 'text' },
      { name: 'tags', label: 'Tags (comma-separated)', type: 'tags' },
      { name: 'is_published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
}
